[workspace]
resolver = "2"         # modern dependency resolver
members = [
  "src/backend/canisters/loans",
  "src/backend/canisters/collateral",
  "src/backend/canisters/repute",
  "src/backend/canisters/trust_ai",
  "src/backend/canisters/event_bus"
]
